# -*- coding: utf-8 -*-
"""Model_Agnijnana

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_KTzcThz5kJGHf1niB9-OiFuhP97V4U
"""

# CELL 1
# Install the current Ultralytics package

!pip -q install -U ultralytics

import ultralytics

print("Ultralytics version:")
print(ultralytics.__version__)

# CELL 2
# Check GPU availability

import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():

    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )

    print(
        "GPU memory:",
        round(
            torch.cuda.get_device_properties(0).total_memory
            / (1024 ** 3),
            2
        ),
        "GB"
    )

else:

    print(
        "⚠️ GPU not available."
    )

# CELL 3

from google.colab import drive

drive.mount(
    "/content/drive"
)

print(
    "✅ Google Drive mounted"
)

# CELL 4

from pathlib import Path

DRIVE_PROJECT = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/Q-SENTINEL-ALLOY-WHEEL"
)

DRIVE_SEG_DATASET = (
    DRIVE_PROJECT /
    "combined_segmentation"
)

DRIVE_DET_DATASET = (
    DRIVE_PROJECT /
    "combined_detection"
)

print("Segmentation dataset:")
print(DRIVE_SEG_DATASET)

print("\nDetection dataset:")
print(DRIVE_DET_DATASET)

print(
    "\nSegmentation YAML exists:",
    (
        DRIVE_SEG_DATASET /
        "data.yaml"
    ).exists()
)

print(
    "Detection YAML exists:",
    (
        DRIVE_DET_DATASET /
        "data.yaml"
    ).exists()
)

# CELL 5

SEG_YAML = (
    DRIVE_SEG_DATASET /
    "data.yaml"
)

required_paths = [
    SEG_YAML,

    DRIVE_SEG_DATASET /
    "images" /
    "train",

    DRIVE_SEG_DATASET /
    "images" /
    "val",

    DRIVE_SEG_DATASET /
    "labels" /
    "train",

    DRIVE_SEG_DATASET /
    "labels" /
    "val"
]

print(
    "SEGMENTATION DATASET CHECK"
)

print(
    "=" * 70
)

all_exist = True

for path in required_paths:

    exists = path.exists()

    print(
        "✅" if exists else "❌",
        path
    )

    if not exists:
        all_exist = False

if not all_exist:

    raise FileNotFoundError(
        "One or more required segmentation dataset paths are missing."
    )

print(
    "\n✅ Dataset structure is present."
)

# CELL 6

import yaml

with open(
    SEG_YAML,
    "r"
) as f:

    seg_config = yaml.safe_load(f)

print(
    yaml.dump(
        seg_config,
        sort_keys=False
    )
)

# CELL 7

def count_images(directory):

    directory = Path(
        directory
    )

    return len([
        f
        for f in directory.rglob("*")
        if f.is_file()
        and f.suffix.lower()
        in [
            ".jpg",
            ".jpeg",
            ".png",
            ".bmp",
            ".webp"
        ]
    ])


for split in [
    "train",
    "val",
    "test"
]:

    image_count = count_images(
        DRIVE_SEG_DATASET /
        "images" /
        split
    )

    label_count = len([
        f
        for f in (
            DRIVE_SEG_DATASET /
            "labels" /
            split
        ).glob("*.txt")
        if f.is_file()
    ])

    print(
        f"{split.upper():5s} | "
        f"Images: {image_count:5d} | "
        f"Labels: {label_count:5d}"
    )

# CELL 8

import shutil

LOCAL_SEG_DATASET = Path(
    "/content/Q-SENTINEL-SEGMENTATION"
)

# Remove previous copy if present
if LOCAL_SEG_DATASET.exists():

    print(
        "Removing previous local dataset..."
    )

    shutil.rmtree(
        LOCAL_SEG_DATASET
    )

print(
    "Copying dataset from Google Drive..."
)

shutil.copytree(
    DRIVE_SEG_DATASET,
    LOCAL_SEG_DATASET
)

print(
    "\n✅ Dataset copied to:"
)

print(
    LOCAL_SEG_DATASET
)

# CELL 9

LOCAL_SEG_YAML = (
    LOCAL_SEG_DATASET /
    "data.yaml"
)

with open(
    LOCAL_SEG_YAML,
    "r"
) as f:

    local_config = yaml.safe_load(f)

local_config["path"] = str(
    LOCAL_SEG_DATASET
)

with open(
    LOCAL_SEG_YAML,
    "w"
) as f:

    yaml.safe_dump(
        local_config,
        f,
        sort_keys=False
    )

print(
    yaml.dump(
        local_config,
        sort_keys=False
    )
)

# CELL 10

from ultralytics.data.utils import check_det_dataset

try:

    checked = check_det_dataset(
        str(LOCAL_SEG_YAML)
    )

    print(
        "✅ Ultralytics accepted the segmentation dataset."
    )

    print(
        "\nDataset root:"
    )

    print(
        checked["path"]
    )

except Exception as e:

    print(
        "❌ Dataset validation failed:"
    )

    print(
        e
    )

    raise

# CELL 11

from ultralytics import YOLO

MODEL_NAME = "yolo26s-seg.pt"

model = YOLO(
    MODEL_NAME
)

print(
    "✅ Model loaded:",
    MODEL_NAME
)

# CELL 12

print(
    model
)

# CELL 13

TRAIN_CONFIG = {

    "data":
        str(LOCAL_SEG_YAML),

    "epochs":
        22,

    "imgsz":
        640,

    "batch":
        -1,

    "device":
        0,

    "workers":
        2,

    "patience":
        6,

    "pretrained":
        True,

    "optimizer":
        "auto",

    "project":
        "/content/Q-SENTINEL-runs",

    "name":
        "alloy_wheel_yolo26s_seg",

    "exist_ok":
        True,

    "save":
        True,

    "plots":
        True,

    "verbose":
        True,
    "seed": 42,
    "deterministic": True
}

print(
    "Training configuration:"
)

for key, value in TRAIN_CONFIG.items():

    print(
        f"{key}: {value}"
    )

from pathlib import Path

RUN_DIR = Path(
    "/content/Q-SENTINEL-runs/alloy_wheel_yolo26s_seg"
)

print("Run directory:", RUN_DIR)

print("\nFiles:")
for f in sorted(RUN_DIR.iterdir()):
    print(f.name)

print("\nWeights:")
for f in sorted(
    (RUN_DIR / "weights").glob("*.pt")
):
    print(
        f.name,
        f.stat().st_size / (1024**2),
        "MB"
    )

import pandas as pd

results_csv = (
    RUN_DIR / "results.csv"
)

results_df = pd.read_csv(
    results_csv
)

print(
    results_df.to_string()
)

# DIAGNOSTIC CELL
# Class distribution in TRAIN / VAL / TEST

from pathlib import Path
from collections import Counter

SEG_DATASET = Path(
    "/content/Q-SENTINEL-SEGMENTATION"
)

CLASS_NAMES = {
    0: "bent_rim",
    1: "crack",
    2: "scratch"
}

for split in ["train", "val", "test"]:

    label_dir = (
        SEG_DATASET
        / "labels"
        / split
    )

    counter = Counter()

    for label_file in label_dir.glob("*.txt"):

        with open(
            label_file,
            "r"
        ) as f:

            for line in f:

                parts = line.strip().split()

                if not parts:
                    continue

                class_id = int(parts[0])

                counter[
                    CLASS_NAMES[class_id]
                ] += 1

    print("\n" + "=" * 60)
    print(split.upper())
    print("=" * 60)

    total = sum(counter.values())

    print(
        "Total instances:",
        total
    )

    for class_name in CLASS_NAMES.values():

        print(
            f"{class_name:15s}: "
            f"{counter[class_name]}"
        )

# CELL 22
# Class distribution by UNIQUE IMAGES

from collections import defaultdict

for split in ["train", "val", "test"]:

    split_dir = (
        LOCAL_SEG_DATASET
        / "labels"
        / split
    )

    class_images = defaultdict(set)
    class_instances = defaultdict(int)

    for label_file in split_dir.glob("*.txt"):

        image_id = label_file.stem

        with open(label_file, "r") as f:

            for line in f:

                parts = line.strip().split()

                if not parts:
                    continue

                class_id = int(parts[0])

                class_name = {
                    0: "bent_rim",
                    1: "crack",
                    2: "scratch"
                }[class_id]

                class_images[class_name].add(
                    image_id
                )

                class_instances[class_name] += 1

    print("\n" + "=" * 60)
    print(split.upper())
    print("=" * 60)

    for class_name in [
        "bent_rim",
        "crack",
        "scratch"
    ]:

        print(
            f"{class_name:12s} | "
            f"Images: {len(class_images[class_name]):4d} | "
            f"Instances: {class_instances[class_name]:4d}"
        )

# CELL 23
# Display representative training examples for each class

import random
import matplotlib.pyplot as plt
import cv2
from pathlib import Path

random.seed(42)

class_names = {
    0: "bent_rim",
    1: "crack",
    2: "scratch"
}

for class_id, class_name in class_names.items():

    candidates = []

    label_dir = (
        LOCAL_SEG_DATASET
        / "labels"
        / "train"
    )

    image_dir = (
        LOCAL_SEG_DATASET
        / "images"
        / "train"
    )

    for label_file in label_dir.glob("*.txt"):

        with open(label_file, "r") as f:

            lines = f.readlines()

        found = False

        for line in lines:

            parts = line.strip().split()

            if parts and int(parts[0]) == class_id:

                found = True
                break

        if found:

            for ext in [
                ".jpg",
                ".jpeg",
                ".png",
                ".bmp",
                ".webp"
            ]:

                image_path = (
                    image_dir
                    / (label_file.stem + ext)
                )

                if image_path.exists():

                    candidates.append(
                        image_path
                    )

                    break

    print(
        f"\n{class_name}: "
        f"{len(candidates)} candidate images"
    )

    samples = random.sample(
        candidates,
        min(6, len(candidates))
    )

    fig, axes = plt.subplots(
        2,
        3,
        figsize=(15, 9)
    )

    axes = axes.flatten()

    for ax, image_path in zip(
        axes,
        samples
    ):

        image = cv2.imread(
            str(image_path)
        )

        image = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2RGB
        )

        ax.imshow(image)
        ax.set_title(
            class_name
        )
        ax.axis("off")

    for ax in axes[len(samples):]:
        ax.axis("off")

    plt.tight_layout()
    plt.show()

# CELL 24
# Class distribution by source dataset

source_class_counts = (
    annotations_df[
        annotations_df["normalized_class"].isin(
            [
                "bent_rim",
                "crack",
                "scratch"
            ]
        )
    ]
    .groupby(
        [
            "dataset",
            "normalized_class"
        ]
    )
    .size()
    .unstack(
        fill_value=0
    )
)

display(
    source_class_counts
)

# CELL 24
# Class distribution in the actual segmentation dataset

from pathlib import Path
from collections import Counter, defaultdict

CLASS_NAMES = {
    0: "bent_rim",
    1: "crack",
    2: "scratch"
}

source_class_counts = defaultdict(Counter)

# ---------------------------------------------------------
# We will inspect the dataset directories directly
# ---------------------------------------------------------

for split in ["train", "val", "test"]:

    label_dir = (
        LOCAL_SEG_DATASET
        / "labels"
        / split
    )

    for label_file in label_dir.glob("*.txt"):

        with open(label_file, "r") as f:

            for line in f:

                parts = line.strip().split()

                if not parts:
                    continue

                class_id = int(parts[0])

                if class_id in CLASS_NAMES:

                    source_class_counts[
                        split
                    ][
                        CLASS_NAMES[class_id]
                    ] += 1


# ---------------------------------------------------------
# Display results
# ---------------------------------------------------------

print("=" * 70)
print("SEGMENTATION DATASET CLASS DISTRIBUTION")
print("=" * 70)

for split in ["train", "val", "test"]:

    print(f"\n{split.upper()}")

    total = sum(
        source_class_counts[split].values()
    )

    print(
        f"Total instances: {total}"
    )

    for class_name in CLASS_NAMES.values():

        count = source_class_counts[
            split
        ][class_name]

        percentage = (
            count / total * 100
            if total > 0
            else 0
        )

        print(
            f"{class_name:15s}: "
            f"{count:4d} "
            f"({percentage:5.1f}%)"
        )

# CELL 25
# Find metadata files from the dataset creation stage

from pathlib import Path

DRIVE_PROJECT = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/Q-SENTINEL-ALLOY-WHEEL"
)

print("=" * 70)
print("METADATA FILES")
print("=" * 70)

for file in DRIVE_PROJECT.rglob("*"):

    if file.is_file() and file.suffix.lower() in [
        ".csv",
        ".json",
        ".xlsx",
        ".parquet"
    ]:

        print(file)

# CELL 14

print(
    "Starting YOLO26-Seg training..."
)

results = model.train(
    **TRAIN_CONFIG
)

print(
    "\n✅ Training completed."
)

from pathlib import Path
import pandas as pd
import json

# ------------------------------------------------------------
# Q-SENTINEL metadata location
# ------------------------------------------------------------
DRIVE_PROJECT = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/Q-SENTINEL-ALLOY-WHEEL"
)
META = DRIVE_PROJECT / "metadata"

# ------------------------------------------------------------
# Load the most important metadata files
# ------------------------------------------------------------
files = {
    "normalized_annotations": META / "all_normalized_annotations.csv",
    "segmentation_index": META / "segmentation_dataset_index.csv",
    "valid_polygons": META / "valid_polygon_annotations.csv",
    "invalid_polygons": META / "invalid_polygon_annotations.csv",
    "splits": META / "image_splits.csv",
    "registry": META / "dataset_registry.csv",
    "class_mapping": META / "class_mapping.csv",
}

dfs = {}

for name, path in files.items():
    if path.exists():
        try:
            dfs[name] = pd.read_csv(path)
            print(f"\n{'='*70}")
            print(f"{name.upper()}")
            print(f"File : {path.name}")
            print(f"Shape: {dfs[name].shape}")
            print(f"Columns: {list(dfs[name].columns)}")
            print(dfs[name].head(3).to_string(index=False))
        except Exception as e:
            print(f"Could not read {path}: {e}")
    else:
        print(f"\nMISSING: {path}")

# ------------------------------------------------------------
# Class mapping JSON
# ------------------------------------------------------------
json_path = META / "class_mapping.json"

if json_path.exists():
    print(f"\n{'='*70}")
    print("CLASS MAPPING JSON")
    with open(json_path, "r") as f:
        class_mapping_json = json.load(f)
    print(json.dumps(class_mapping_json, indent=2))

import pandas as pd
from pathlib import Path

ann = dfs["normalized_annotations"].copy()
seg = dfs["segmentation_index"].copy()

print("=" * 70)
print("Q-SENTINEL DATASET DIAGNOSTIC")
print("=" * 70)

# ------------------------------------------------------------
# Helper to find a likely column
# ------------------------------------------------------------
def find_col(df, candidates):
    cols_lower = {c.lower(): c for c in df.columns}

    # exact lowercase match
    for candidate in candidates:
        if candidate.lower() in cols_lower:
            return cols_lower[candidate.lower()]

    # substring match
    for c in df.columns:
        cl = c.lower()
        for candidate in candidates:
            if candidate.lower() in cl:
                return c

    return None


class_col = find_col(
    ann,
    ["class_name", "class", "defect_class", "normalized_class", "label"]
)

source_col = find_col(
    ann,
    ["source_dataset", "dataset", "source", "dataset_name", "registry_name"]
)

image_col = find_col(
    ann,
    ["image", "image_name", "filename", "file_name", "image_path"]
)

print("\nDetected columns:")
print("Class  :", class_col)
print("Source :", source_col)
print("Image  :", image_col)

# ------------------------------------------------------------
# 1. Overall annotation distribution
# ------------------------------------------------------------
if class_col:
    print("\n" + "=" * 70)
    print("OVERALL CLASS DISTRIBUTION")
    print("=" * 70)

    class_counts = ann[class_col].value_counts()

    for cls, count in class_counts.items():
        print(f"{str(cls):35s} {count:5d}")

# ------------------------------------------------------------
# 2. Source dataset distribution
# ------------------------------------------------------------
if source_col:
    print("\n" + "=" * 70)
    print("SOURCE DATASET DISTRIBUTION")
    print("=" * 70)

    source_counts = ann[source_col].value_counts()

    for source, count in source_counts.items():
        print(f"{str(source):45s} {count:5d}")

# ------------------------------------------------------------
# 3. Source x class
# ------------------------------------------------------------
if source_col and class_col:
    print("\n" + "=" * 70)
    print("SOURCE × CLASS")
    print("=" * 70)

    source_class = pd.crosstab(
        ann[source_col],
        ann[class_col]
    )

    print(source_class.to_string())

# ------------------------------------------------------------
# 4. Number of unique images per class
# ------------------------------------------------------------
if class_col and image_col:
    print("\n" + "=" * 70)
    print("UNIQUE IMAGES PER CLASS")
    print("=" * 70)

    unique_images = (
        ann.groupby(class_col)[image_col]
        .nunique()
        .sort_values(ascending=False)
    )

    for cls, count in unique_images.items():
        print(f"{str(cls):35s} {count:5d}")

# ------------------------------------------------------------
# 5. Valid vs invalid polygon annotations
# ------------------------------------------------------------
valid_df = dfs.get("valid_polygons")
invalid_df = dfs.get("invalid_polygons")

print("\n" + "=" * 70)
print("POLYGON ANNOTATION QUALITY")
print("=" * 70)

if valid_df is not None:
    print("Valid polygon annotations  :", len(valid_df))

if invalid_df is not None:
    print("Invalid polygon annotations:", len(invalid_df))

# ------------------------------------------------------------
# 6. Segmentation dataset image count
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SEGMENTATION DATASET")
print("=" * 70)

print("Segmentation index rows:", len(seg))

if image_col and image_col in seg.columns:
    print(
        "Unique segmentation images:",
        seg[image_col].nunique()
    )

import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

LOCAL_SEG_DATASET = Path("/content/Q-SENTINEL-SEGMENTATION")

names = ["bent_rim", "crack", "scratch"]

for split in ["train"]:
    image_dir = LOCAL_SEG_DATASET / "images" / split
    label_dir = LOCAL_SEG_DATASET / "labels" / split

    print("\n" + "=" * 70)
    print(f"VISUAL QA — {split.upper()}")
    print("=" * 70)

    image_files = list(image_dir.glob("*"))

    for cls_id, cls_name in enumerate(names):

        candidates = []

        for img_path in image_files:
            label_path = label_dir / f"{img_path.stem}.txt"

            if not label_path.exists():
                continue

            text = label_path.read_text().strip()

            if not text:
                continue

            for line in text.splitlines():
                parts = line.split()

                if len(parts) < 7:
                    continue

                if int(parts[0]) == cls_id:
                    candidates.append(img_path)
                    break

        print(f"{cls_name}: {len(candidates)} candidate images")

        if not candidates:
            continue

        sample = random.sample(
            candidates,
            min(3, len(candidates))
        )

        for img_path in sample:

            img = cv2.imread(str(img_path))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            h, w = img.shape[:2]

            label_path = label_dir / f"{img_path.stem}.txt"

            plt.figure(figsize=(7, 7))
            plt.imshow(img)

            for line in label_path.read_text().strip().splitlines():
                parts = line.split()

                if len(parts) < 7:
                    continue

                cid = int(parts[0])

                if cid != cls_id:
                    continue

                coords = np.array(
                    list(map(float, parts[1:])),
                    dtype=np.float32
                ).reshape(-1, 2)

                coords[:, 0] *= w
                coords[:, 1] *= h

                polygon = np.vstack([coords, coords[0]])

                plt.plot(
                    polygon[:, 0],
                    polygon[:, 1],
                    linewidth=2
                )

            plt.title(f"{cls_name} — {img_path.name}")
            plt.axis("off")
            plt.show()

from pathlib import Path
import pandas as pd

DRIVE_PROJECT = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/Q-SENTINEL-ALLOY-WHEEL"
)

invalid_path = DRIVE_PROJECT / "metadata" / "invalid_polygon_annotations.csv"

print("Checking file:")
print(invalid_path)
print("Exists:", invalid_path.exists())

if invalid_path.exists():
    invalid_df = pd.read_csv(invalid_path)

    print("\n" + "=" * 70)
    print("INVALID POLYGON ANNOTATIONS")
    print("=" * 70)

    print("Rows:", len(invalid_df))
    print("Columns:", list(invalid_df.columns))

    if len(invalid_df) > 0:
        print("\nFirst 20 rows:")
        display(invalid_df.head(20))

        # Automatically identify a likely class column
        possible_class_cols = [
            "class_name",
            "class",
            "defect_class",
            "normalized_class",
            "label"
        ]

        class_col = None

        for col in possible_class_cols:
            if col in invalid_df.columns:
                class_col = col
                break

        if class_col:
            print("\nInvalid polygons by class:")
            print(
                invalid_df[class_col]
                .value_counts()
                .to_string()
            )
        else:
            print("\nNo obvious class column found.")

    else:
        print("\n✅ No invalid polygon annotations were recorded.")

else:
    print("\n❌ File does not exist at the expected path.")

from pathlib import Path

invalid_path = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/"
    "Q-SENTINEL-ALLOY-WHEEL/metadata/invalid_polygon_annotations.csv"
)

print("Exists:", invalid_path.exists())
print("Size:", invalid_path.stat().st_size, "bytes")

with open(invalid_path, "rb") as f:
    content = f.read()

print("Raw content:", repr(content))

from pathlib import Path
import pandas as pd

PROJECT = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/"
    "Q-SENTINEL-ALLOY-WHEEL"
)

valid_path = PROJECT / "metadata" / "valid_polygon_annotations.csv"

print("Exists:", valid_path.exists())
print("Size:", valid_path.stat().st_size, "bytes")

if valid_path.stat().st_size == 0:
    print("❌ valid_polygon_annotations.csv is also empty.")
else:
    valid_df = pd.read_csv(valid_path)

    print("\nRows:", len(valid_df))
    print("Columns:", list(valid_df.columns))

    display(valid_df.head(10))

seg_path = PROJECT / "metadata" / "segmentation_dataset_index.csv"

print("Exists:", seg_path.exists())
print("Size:", seg_path.stat().st_size, "bytes")

if seg_path.stat().st_size == 0:
    print("❌ segmentation_dataset_index.csv is empty.")
else:
    seg_df = pd.read_csv(seg_path)

    print("\nRows:", len(seg_df))
    print("Columns:", list(seg_df.columns))

    display(seg_df.head(10))

ann_path = PROJECT / "metadata" / "all_normalized_annotations.csv"

print("Exists:", ann_path.exists())
print("Size:", ann_path.stat().st_size, "bytes")

ann = pd.read_csv(ann_path)

print("\nRows:", len(ann))
print("Columns:")
print(list(ann.columns))

display(ann.head(10))

# ============================================================
# Q-SENTINEL — VALID POLYGON DATASET ANALYSIS
# ============================================================

print("=" * 80)
print("VALID POLYGON ANNOTATION ANALYSIS")
print("=" * 80)

# ------------------------------------------------------------
# 1. Basic statistics
# ------------------------------------------------------------

print("\nTotal valid polygon annotations:", len(valid_df))

print(
    "Unique images:",
    valid_df["image_path"].nunique()
)

print(
    "Unique duplicate groups:",
    valid_df["duplicate_group"].nunique()
)

print(
    "Annotation types:",
    valid_df["annotation_type"].value_counts().to_dict()
)

# ------------------------------------------------------------
# 2. Class distribution
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("CLASS DISTRIBUTION")
print("=" * 80)

class_counts = (
    valid_df["normalized_class"]
    .value_counts()
)

class_percent = (
    class_counts / class_counts.sum() * 100
).round(2)

class_table = pd.DataFrame({
    "annotations": class_counts,
    "percentage": class_percent
})

display(class_table)

# ------------------------------------------------------------
# 3. Unique images per class
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("UNIQUE IMAGES PER CLASS")
print("=" * 80)

image_class_counts = (
    valid_df
    .groupby("normalized_class")["image_path"]
    .nunique()
    .sort_values(ascending=False)
)

display(
    image_class_counts.to_frame("unique_images")
)

# ------------------------------------------------------------
# 4. Source dataset distribution
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("SOURCE DATASET DISTRIBUTION")
print("=" * 80)

source_counts = (
    valid_df["dataset"]
    .value_counts()
)

source_percent = (
    source_counts / source_counts.sum() * 100
).round(2)

source_table = pd.DataFrame({
    "annotations": source_counts,
    "percentage": source_percent
})

display(source_table)

# ------------------------------------------------------------
# 5. SOURCE × CLASS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("SOURCE DATASET × NORMALIZED CLASS")
print("=" * 80)

source_class = pd.crosstab(
    valid_df["dataset"],
    valid_df["normalized_class"]
)

display(source_class)

# ------------------------------------------------------------
# 6. Number of classes per image
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("IMAGES CONTAINING MULTIPLE DEFECT CLASSES")
print("=" * 80)

classes_per_image = (
    valid_df
    .groupby("image_path")["normalized_class"]
    .nunique()
)

print(
    "Images with 1 class :",
    (classes_per_image == 1).sum()
)

print(
    "Images with >1 class:",
    (classes_per_image > 1).sum()
)

# ------------------------------------------------------------
# 7. Objects per image
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("OBJECTS PER IMAGE")
print("=" * 80)

objects_per_image = (
    valid_df
    .groupby("image_path")
    .size()
)

print("Minimum objects/image:", objects_per_image.min())
print("Maximum objects/image:", objects_per_image.max())
print("Average objects/image:", round(objects_per_image.mean(), 2))
print("Median objects/image:", objects_per_image.median())

# ------------------------------------------------------------
# 8. Duplicate groups spanning multiple images
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("DUPLICATE GROUP ANALYSIS")
print("=" * 80)

group_sizes = (
    valid_df
    .groupby("duplicate_group")["image_path"]
    .nunique()
)

print(
    "Duplicate groups containing >1 image:",
    (group_sizes > 1).sum()
)

print(
    "Maximum images in one duplicate group:",
    group_sizes.max()
)

# ============================================================
# Q-SENTINEL — ACTUAL YOLO SEGMENTATION LABEL ANALYSIS
# ============================================================

from pathlib import Path
from collections import Counter

LOCAL_SEG_DATASET = Path("/content/Q-SENTINEL-SEGMENTATION")

CLASS_NAMES = {
    0: "bent_rim",
    1: "crack",
    2: "scratch"
}

print("=" * 80)
print("ACTUAL YOLO SEGMENTATION DATASET")
print("=" * 80)

total_instances = 0
total_images = 0

for split in ["train", "val", "test"]:

    image_dir = LOCAL_SEG_DATASET / "images" / split
    label_dir = LOCAL_SEG_DATASET / "labels" / split

    image_files = list(image_dir.glob("*"))
    label_files = list(label_dir.glob("*.txt"))

    counts = Counter()

    for label_file in label_files:

        lines = label_file.read_text().strip().splitlines()

        for line in lines:

            if not line.strip():
                continue

            parts = line.split()

            # Segmentation format:
            # class_id x1 y1 x2 y2 ...
            if len(parts) >= 7:

                class_id = int(parts[0])

                if class_id in CLASS_NAMES:
                    counts[class_id] += 1

    split_instances = sum(counts.values())

    total_instances += split_instances
    total_images += len(image_files)

    print(f"\n{split.upper()}")
    print("-" * 40)
    print("Images:", len(image_files))
    print("Instances:", split_instances)

    for cid, cname in CLASS_NAMES.items():
        print(
            f"{cname:12s}: {counts[cid]}"
        )

print("\n" + "=" * 80)
print("TOTAL")
print("=" * 80)

print("Total images:", total_images)
print("Total instances:", total_instances)

print("\nMetadata valid polygons:", len(valid_df))
print(
    "Difference:",
    len(valid_df) - total_instances
)

# ============================================================
# Q-SENTINEL — TARGET SEGMENTATION CLASS RETENTION
# ============================================================

TARGET_CLASSES = ["bent_rim", "crack", "scratch"]

print("=" * 80)
print("VALID POLYGONS → TARGET SEGMENTATION CLASSES")
print("=" * 80)

# Metadata counts
metadata_target = (
    valid_df[
        valid_df["normalized_class"].isin(TARGET_CLASSES)
    ]["normalized_class"]
    .value_counts()
    .reindex(TARGET_CLASSES, fill_value=0)
)

# Actual YOLO segmentation counts
actual_target = {
    "bent_rim": 339 + 41 + 49,
    "crack": 291 + 34 + 42,
    "scratch": 920 + 170 + 95
}

comparison = pd.DataFrame({
    "metadata_valid_polygons": metadata_target,
    "actual_segmentation_instances": pd.Series(actual_target)
})

comparison["not_used"] = (
    comparison["metadata_valid_polygons"]
    - comparison["actual_segmentation_instances"]
)

comparison["retention_%"] = (
    comparison["actual_segmentation_instances"]
    / comparison["metadata_valid_polygons"].replace(0, np.nan)
    * 100
).round(2)

display(comparison)

# ============================================================
# Q-SENTINEL — WHERE DID THE 1,319 POLYGONS GO?
# ============================================================

print("=" * 80)
print("ALL VALID POLYGON CLASSES")
print("=" * 80)

all_class_counts = (
    valid_df["normalized_class"]
    .value_counts()
)

all_class_percentage = (
    all_class_counts / len(valid_df) * 100
).round(2)

all_classes = pd.DataFrame({
    "valid_polygon_annotations": all_class_counts,
    "percentage": all_class_percentage
})

display(all_classes)

# ============================================================
# Q-SENTINEL — EXACT TARGET POLYGON TOTAL
# ============================================================

target_metadata_total = (
    valid_df[
        valid_df["normalized_class"].isin(TARGET_CLASSES)
    ].shape[0]
)

actual_segmentation_total = 1981

print("Valid polygons in metadata        :", len(valid_df))
print("Valid polygons for target classes:",
      target_metadata_total)
print("Actual segmentation instances    :",
      actual_segmentation_total)

print(
    "\nDifference between target metadata and actual:",
    target_metadata_total - actual_segmentation_total
)

# CELL 15

RUN_DIR = Path(
    "/content/Q-SENTINEL-runs/alloy_wheel_yolo26s_seg"
)

print(
    "Training run directory:"
)

print(
    RUN_DIR
)

if RUN_DIR.exists():

    print(
        "\nFiles:"
    )

    for f in sorted(
        RUN_DIR.iterdir()
    ):

        print(
            "📁" if f.is_dir()
            else "📄",
            f.name
        )

else:

    print(
        "❌ Run directory not found."
    )

# CELL 16

BEST_MODEL = (
    RUN_DIR /
    "weights" /
    "best.pt"
)

LAST_MODEL = (
    RUN_DIR /
    "weights" /
    "last.pt"
)

print(
    "Best model exists:",
    BEST_MODEL.exists()
)

print(
    "Last model exists:",
    LAST_MODEL.exists()
)

if BEST_MODEL.exists():

    size_mb = (
        BEST_MODEL.stat().st_size
        /
        (1024 ** 2)
    )

    print(
        f"\nBest model size: {size_mb:.2f} MB"
    )

# CELL 17

best_model = YOLO(
    str(BEST_MODEL)
)

validation_results = best_model.val(
    data=str(LOCAL_SEG_YAML),
    split="val",
    imgsz=640,
    device=0,
    plots=True
)

print(
    "\n✅ Validation complete."
)

# CELL 18

print(
    "VALIDATION METRICS"
)

print(
    "=" * 60
)

try:

    print(
        "Box mAP50:",
        validation_results.box.map50
    )

    print(
        "Box mAP50-95:",
        validation_results.box.map
    )

    print(
        "Mask mAP50:",
        validation_results.seg.map50
    )

    print(
        "Mask mAP50-95:",
        validation_results.seg.map
    )

except Exception as e:

    print(
        "Could not read all metrics:",
        e
    )

    print(
        validation_results
    )

# CELL 19

try:

    print(
        "PER-CLASS SEGMENTATION RESULTS"
    )

    print(
        "=" * 80
    )

    class_maps = (
        validation_results.seg.maps
    )

    class_names = (
        local_config["names"]
    )

    if isinstance(
        class_names,
        dict
    ):

        class_names = {
            int(k): v
            for k, v
            in class_names.items()
        }

    for idx, metric in enumerate(
        class_maps
    ):

        print(
            f"{class_names[idx]:20s}"
            f" → mAP50-95 = {metric:.4f}"
        )

except Exception as e:

    print(
        "Per-class metrics could not be displayed:"
    )

    print(
        e
    )

# CELL 20

TEST_IMAGE_DIR = (
    LOCAL_SEG_DATASET /
    "images" /
    "test"
)

test_images = [
    f
    for f in TEST_IMAGE_DIR.iterdir()
    if f.is_file()
    and f.suffix.lower()
    in [
        ".jpg",
        ".jpeg",
        ".png",
        ".bmp",
        ".webp"
    ]
]

print(
    "Test images:",
    len(test_images)
)

sample_test_images = test_images[
    :10
]

print(
    "\nRunning inference on:",
    len(sample_test_images),
    "images"
)

prediction_results = best_model.predict(
    source=[
        str(f)
        for f in sample_test_images
    ],
    imgsz=640,
    conf=0.25,
    device=0,
    save=True,
    project="/content/Q-SENTINEL-predictions",
    name="test_samples",
    exist_ok=True
)

print(
    "\n✅ Test inference completed."
)

# CELL 21

from IPython.display import display
from PIL import Image

PREDICTION_DIR = Path(
    "/content/Q-SENTINEL-predictions/test_samples"
)

prediction_files = [
    f
    for f in PREDICTION_DIR.iterdir()
    if f.is_file()
    and f.suffix.lower()
    in [
        ".jpg",
        ".jpeg",
        ".png"
    ]
]

print(
    "Prediction images:",
    len(prediction_files)
)

for image_path in prediction_files[:10]:

    print(
        image_path.name
    )

    display(
        Image.open(
            image_path
        )
    )

# CELL 22

try:

    evaluation_results = best_model.val(
        data=str(LOCAL_SEG_YAML),
        split="test",
        imgsz=640,
        device=0,
        plots=True
    )

    print(
        "✅ Test evaluation completed."
    )

    print(
        "\nTest Mask mAP50:",
        evaluation_results.seg.map50
    )

    print(
        "Test Mask mAP50-95:",
        evaluation_results.seg.map
    )

except Exception as e:

    print(
        "Test evaluation encountered an issue:"
    )

    print(
        e
    )

# CELL 23

from pathlib import Path
import shutil

DRIVE_MODEL_DIR = (
    DRIVE_PROJECT /
    "models" /
    "yolo26s_seg"
)

DRIVE_MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Copy best.pt
if BEST_MODEL.exists():

    shutil.copy2(
        BEST_MODEL,
        DRIVE_MODEL_DIR /
        "best.pt"
    )

# Copy last.pt
if LAST_MODEL.exists():

    shutil.copy2(
        LAST_MODEL,
        DRIVE_MODEL_DIR /
        "last.pt"
    )

print(
    "✅ Model weights saved to Drive:"
)

print(
    DRIVE_MODEL_DIR
)

# CELL 24

DRIVE_RUN_DIR = (
    DRIVE_PROJECT /
    "models" /
    "yolo26s_seg" /
    "training_run"
)

if DRIVE_RUN_DIR.exists():

    shutil.rmtree(
        DRIVE_RUN_DIR
    )

shutil.copytree(
    RUN_DIR,
    DRIVE_RUN_DIR
)

print(
    "✅ Full training run copied to Drive:"
)

print(
    DRIVE_RUN_DIR
)

# CELL 25

experiment_record = {

    "model":
        "YOLO26s-Seg",

    "task":
        "Instance Segmentation",

    "component":
        "Automotive Alloy Wheel",

    "classes":
        [
            "bent_rim",
            "crack",
            "scratch"
        ],

    "epochs":
        TRAIN_CONFIG["epochs"],

    "image_size":
        TRAIN_CONFIG["imgsz"],

    "dataset":
        str(DRIVE_SEG_DATASET),

    "training_runtime_dataset":
        str(LOCAL_SEG_DATASET),

    "best_model":
        str(
            DRIVE_MODEL_DIR /
            "best.pt"
        ),

    "box_mAP50":
        float(
            validation_results.box.map50
        )
        if hasattr(
            validation_results,
            "box"
        )
        else None,

    "box_mAP50_95":
        float(
            validation_results.box.map
        )
        if hasattr(
            validation_results,
            "box"
        )
        else None,

    "mask_mAP50":
        float(
            validation_results.seg.map50
        )
        if hasattr(
            validation_results,
            "seg"
        )
        else None,

    "mask_mAP50_95":
        float(
            validation_results.seg.map
        )
        if hasattr(
            validation_results,
            "seg"
        )
        else None
}

EXPERIMENT_FILE = (
    DRIVE_MODEL_DIR /
    "experiment.json"
)

with open(
    EXPERIMENT_FILE,
    "w"
) as f:

    json.dump(
        experiment_record,
        f,
        indent=4
    )

print(
    "✅ Experiment record saved:"
)

print(
    EXPERIMENT_FILE
)

# CELL 26

print(
    "FINAL YOLO26-Seg MODEL CHECK"
)

print(
    "=" * 70
)

files_to_check = [

    DRIVE_MODEL_DIR /
    "best.pt",

    DRIVE_MODEL_DIR /
    "last.pt",

    DRIVE_MODEL_DIR /
    "experiment.json",

    DRIVE_RUN_DIR /
    "results.csv",

    DRIVE_RUN_DIR /
    "results.png"
]

all_present = True

for path in files_to_check:

    exists = path.exists()

    print(
        "✅" if exists else "❌",
        path
    )

    if not exists:
        all_present = False

if all_present:

    print(
        "\n✅ YOLO26-Seg training artifacts are safely stored in Drive."
    )

else:

    print(
        "\n⚠️ Some training artifacts are missing."
    )





"""YOLO skipped, continue with CNN_Transformer"""

# ============================================================
# Q-SENTINEL — DEFECT CROP DATASET INSPECTION
# ============================================================

from pathlib import Path
import pandas as pd

PROJECT = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/"
    "Q-SENTINEL-ALLOY-WHEEL"
)

CROP_META = PROJECT / "metadata" / "defect_crops.csv"

print("=" * 80)
print("Q-SENTINEL DEFECT CROP DATASET")
print("=" * 80)

print("\nFile:")
print(CROP_META)

print("\nExists:", CROP_META.exists())

if CROP_META.exists():

    print("Size:", CROP_META.stat().st_size, "bytes")

    crops_df = pd.read_csv(CROP_META)

    print("\nRows:", len(crops_df))

    print("\nColumns:")
    for col in crops_df.columns:
        print(" -", col)

    print("\nFirst 10 records:")
    display(crops_df.head(10))

else:
    raise FileNotFoundError(
        f"Could not find {CROP_META}"
    )

# ============================================================
# CLASS DISTRIBUTION
# ============================================================

print("=" * 80)
print("DEFECT CROP CLASS DISTRIBUTION")
print("=" * 80)

# Try to automatically identify the class column
possible_class_columns = [
    "normalized_class",
    "class_name",
    "defect_class",
    "class",
    "label"
]

CLASS_COL = None

for col in possible_class_columns:
    if col in crops_df.columns:
        CLASS_COL = col
        break

print("Detected class column:", CLASS_COL)

if CLASS_COL is None:
    print("\nCould not automatically identify the class column.")
else:

    counts = crops_df[CLASS_COL].value_counts()

    percentages = (
        counts / counts.sum() * 100
    ).round(2)

    class_distribution = pd.DataFrame({
        "crop_count": counts,
        "percentage": percentages
    })

    display(class_distribution)

    print("\nNumber of classes:",
          crops_df[CLASS_COL].nunique())

from pathlib import Path
import pandas as pd

PROJECT = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/"
    "Q-SENTINEL-ALLOY-WHEEL"
)

CROP_CSV = PROJECT / "metadata" / "defect_crops.csv"

crops_df = pd.read_csv(CROP_CSV)

print("=" * 80)
print("Q-SENTINEL DEFECT CROPS")
print("=" * 80)

print("Rows:", len(crops_df))

print("\nColumns:")
for c in crops_df.columns:
    print(" -", c)

print("\nFirst 5 rows:")
display(crops_df.head())

print("=" * 80)
print("CROP DATASET STRUCTURE")
print("=" * 80)

for col in crops_df.columns:

    print(f"\n[{col}]")
    print("dtype:", crops_df[col].dtype)
    print("unique:", crops_df[col].nunique())

    if crops_df[col].nunique() <= 20:
        print(crops_df[col].value_counts().to_string())

TARGET_CLASSES = [
    "scratch",
    "blow_hole",
    "incomplete_welding",
    "bent_rim",
    "crack",
    "porosity",
    "scuff",
    "paint_damage"
]

# ============================================================
# Q-SENTINEL — 8-CLASS CLASSIFICATION DATASET PREPARATION
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT = Path(
    "/content/drive/MyDrive/Q-SENTINEL/dataset/"
    "Q-SENTINEL-ALLOY-WHEEL"
)

CROP_META = PROJECT / "metadata" / "defect_crops.csv"

# ------------------------------------------------------------
# Load metadata
# ------------------------------------------------------------

df = pd.read_csv(CROP_META)

print("=" * 80)
print("LOADED DEFECT CROPS")
print("=" * 80)
print("Rows:", len(df))
print("Columns:", list(df.columns))

# ------------------------------------------------------------
# Target classes
# ------------------------------------------------------------

TARGET_CLASSES = [
    "scratch",
    "blow_hole",
    "incomplete_welding",
    "bent_rim",
    "crack",
    "porosity",
    "scuff",
    "paint_damage"
]

CLASS_COL = "class_name"

# ------------------------------------------------------------
# Detect crop path column
# ------------------------------------------------------------

path_candidates = [
    "crop_path",
    "path",
    "file_path",
    "image_path",
    "crop_image_path",
    "filename"
]

CROP_COL = None

for col in path_candidates:
    if col in df.columns:
        CROP_COL = col
        break

if CROP_COL is None:
    raise ValueError(
        "Could not identify the crop path column. "
        f"Available columns: {list(df.columns)}"
    )

print("\nCrop path column:", CROP_COL)

# ------------------------------------------------------------
# Filter target classes
# ------------------------------------------------------------

df = df[
    df[CLASS_COL].isin(TARGET_CLASSES)
].copy()

print("\nTarget-class rows:", len(df))

# ------------------------------------------------------------
# Remove records with missing paths
# ------------------------------------------------------------

df = df[
    df[CROP_COL].notna() &
    (df[CROP_COL].astype(str).str.strip() != "")
].copy()

# ------------------------------------------------------------
# Verify crop files
# ------------------------------------------------------------

df["crop_exists"] = df[CROP_COL].apply(
    lambda x: Path(str(x)).exists()
)

missing = df[~df["crop_exists"]].copy()

print("Existing crop files:", df["crop_exists"].sum())
print("Missing crop files :", len(missing))

if len(missing) > 0:
    print("\nFirst missing files:")
    display(missing[[CLASS_COL, CROP_COL]].head(20))

df = df[df["crop_exists"]].copy()

# ------------------------------------------------------------
# Remove exact duplicate crop paths
# ------------------------------------------------------------

before = len(df)

df = df.drop_duplicates(
    subset=[CROP_COL]
).copy()

print(
    "\nDuplicate crop records removed:",
    before - len(df)
)

# ------------------------------------------------------------
# Show final class distribution
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("FINAL 8-CLASS DATASET")
print("=" * 80)

distribution = (
    df[CLASS_COL]
    .value_counts()
    .reindex(TARGET_CLASSES, fill_value=0)
)

distribution_df = pd.DataFrame({
    "class": distribution.index,
    "count": distribution.values,
    "percentage": (
        distribution.values /
        distribution.values.sum() * 100
    ).round(2)
})

display(distribution_df)

print("\nTotal usable crops:", len(df))

# ============================================================
# LEAKAGE-SAFE GROUP SPLIT
# ============================================================

from sklearn.model_selection import GroupShuffleSplit

# ------------------------------------------------------------
# Determine grouping column
# ------------------------------------------------------------

if "duplicate_group" in df.columns:
    # Duplicate/near-duplicate group is the safest grouping unit
    df["_split_group"] = (
        df["duplicate_group"]
        .fillna(df[CROP_COL].astype(str))
        .astype(str)
    )

elif "image_path" in df.columns:
    # Multiple defect crops from the same original image stay together
    df["_split_group"] = df["image_path"].astype(str)

else:
    # Fallback: each crop becomes its own group
    df["_split_group"] = df[CROP_COL].astype(str)

print("Grouping column prepared.")
print("Unique groups:", df["_split_group"].nunique())

# ------------------------------------------------------------
# Repeated group split
# ------------------------------------------------------------

TARGET_TRAIN = 0.70
TARGET_VAL = 0.15
TARGET_TEST = 0.15

best_split = None
best_score = float("inf")

# Overall class distribution
overall = (
    df[CLASS_COL]
    .value_counts(normalize=True)
    .reindex(TARGET_CLASSES, fill_value=0)
    .values
)

for seed in range(100, 600):

    # First: 70% train / 30% temporary
    gss1 = GroupShuffleSplit(
        n_splits=1,
        test_size=0.30,
        random_state=seed
    )

    train_idx, temp_idx = next(
        gss1.split(
            df,
            groups=df["_split_group"]
        )
    )

    train_df = df.iloc[train_idx].copy()
    temp_df = df.iloc[temp_idx].copy()

    # Second: 50/50 validation/test
    gss2 = GroupShuffleSplit(
        n_splits=1,
        test_size=0.50,
        random_state=seed
    )

    val_idx, test_idx = next(
        gss2.split(
            temp_df,
            groups=temp_df["_split_group"]
        )
    )

    val_df = temp_df.iloc[val_idx].copy()
    test_df = temp_df.iloc[test_idx].copy()

    # Every target class should appear in every split
    valid = True

    for split_df in [train_df, val_df, test_df]:
        counts = (
            split_df[CLASS_COL]
            .value_counts()
            .reindex(TARGET_CLASSES, fill_value=0)
        )

        if (counts == 0).any():
            valid = False
            break

    if not valid:
        continue

    # Compare distributions with global distribution
    score = 0

    for split_df, target_size in [
        (train_df, TARGET_TRAIN),
        (val_df, TARGET_VAL),
        (test_df, TARGET_TEST)
    ]:

        actual_size = len(split_df) / len(df)

        # Split-size error
        score += 10 * (actual_size - target_size) ** 2

        # Class-distribution error
        actual_distribution = (
            split_df[CLASS_COL]
            .value_counts(normalize=True)
            .reindex(TARGET_CLASSES, fill_value=0)
            .values
        )

        score += np.mean(
            (actual_distribution - overall) ** 2
        )

    if score < best_score:
        best_score = score
        best_split = (
            train_df.copy(),
            val_df.copy(),
            test_df.copy()
        )

if best_split is None:
    raise RuntimeError(
        "Could not find a valid group split with "
        "all 8 classes represented in train/val/test."
    )

train_df, val_df, test_df = best_split

# ------------------------------------------------------------
# Add split labels
# ------------------------------------------------------------

train_df["split"] = "train"
val_df["split"] = "val"
test_df["split"] = "test"

split_df = pd.concat(
    [train_df, val_df, test_df],
    ignore_index=True
)

# ------------------------------------------------------------
# Display split statistics
# ------------------------------------------------------------

print("=" * 80)
print("LEAKAGE-SAFE SPLIT")
print("=" * 80)

for name, part in [
    ("TRAIN", train_df),
    ("VAL", val_df),
    ("TEST", test_df)
]:

    print(f"\n{name}")
    print("-" * 40)
    print("Crops :", len(part))
    print("Groups:", part["_split_group"].nunique())

    counts = (
        part[CLASS_COL]
        .value_counts()
        .reindex(TARGET_CLASSES, fill_value=0)
    )

    print(counts.to_string())

# ------------------------------------------------------------
# Verify no group leakage
# ------------------------------------------------------------

train_groups = set(train_df["_split_group"])
val_groups = set(val_df["_split_group"])
test_groups = set(test_df["_split_group"])

print("\n" + "=" * 80)
print("LEAKAGE CHECK")
print("=" * 80)

print("Train ∩ Val :", len(train_groups & val_groups))
print("Train ∩ Test:", len(train_groups & test_groups))
print("Val ∩ Test  :", len(val_groups & test_groups))

assert len(train_groups & val_groups) == 0
assert len(train_groups & test_groups) == 0
assert len(val_groups & test_groups) == 0

print("\n✅ No group leakage detected.")

# ============================================================
# SAVE CLASSIFICATION SPLIT
# ============================================================

OUTPUT_META = PROJECT / "metadata"

OUTPUT_META.mkdir(
    parents=True,
    exist_ok=True
)

split_csv = OUTPUT_META / "classification_split_8class.csv"

# Remove internal helper column if desired
save_df = split_df.drop(
    columns=["crop_exists"],
    errors="ignore"
)

save_df.to_csv(
    split_csv,
    index=False
)

print("Saved:")
print(split_csv)

print("\nSplit totals:")
print(save_df["split"].value_counts())

# ============================================================
# CREATE LOCAL CLASSIFICATION DATASET
# ============================================================

import shutil

LOCAL_CLS = Path("/content/Q-SENTINEL-CLS")

if LOCAL_CLS.exists():
    shutil.rmtree(LOCAL_CLS)

for split in ["train", "val", "test"]:
    for cls in TARGET_CLASSES:
        (LOCAL_CLS / split / cls).mkdir(
            parents=True,
            exist_ok=True
        )

print("Local dataset directory created:")
print(LOCAL_CLS)

# ============================================================
# COPY CROPS TO LOCAL DATASET
# ============================================================

from tqdm.auto import tqdm

copy_errors = []

for split in ["train", "val", "test"]:

    part = split_df[
        split_df["split"] == split
    ]

    print(f"\nCopying {split}: {len(part)} crops")

    for idx, row in tqdm(
        part.iterrows(),
        total=len(part)
    ):

        src = Path(str(row[CROP_COL]))

        # Use unique filenames to avoid collisions
        suffix = src.suffix.lower()

        if suffix not in [".jpg", ".jpeg", ".png", ".bmp", ".webp"]:
            suffix = ".jpg"

        dst = (
            LOCAL_CLS /
            split /
            str(row[CLASS_COL]) /
            f"{idx:07d}{suffix}"
        )

        try:
            shutil.copy2(src, dst)
        except Exception as e:
            copy_errors.append({
                "source": str(src),
                "destination": str(dst),
                "error": str(e)
            })

print("\nCopy errors:", len(copy_errors))

if copy_errors:
    display(pd.DataFrame(copy_errors).head(20))
else:
    print("✅ All crops copied successfully.")

# ============================================================
# VERIFY LOCAL DATASET
# ============================================================

for split in ["train", "val", "test"]:

    print("\n" + "=" * 70)
    print(split.upper())
    print("=" * 70)

    total = 0

    for cls in TARGET_CLASSES:

        folder = LOCAL_CLS / split / cls

        count = len([
            f for f in folder.iterdir()
            if f.is_file()
        ])

        total += count

        print(f"{cls:25s}: {count:5d}")

    print("-" * 40)
    print(f"{'TOTAL':25s}: {total:5d}")

# ============================================================
# Q-SENTINEL — CONVNEXT ENVIRONMENT
# ============================================================

import torch
import torchvision
import sklearn
import pandas as pd
import numpy as np

print("PyTorch      :", torch.__version__)
print("TorchVision  :", torchvision.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# ============================================================
# CONVNEXT-TINY TRAINING CONFIGURATION
# ============================================================

from pathlib import Path
import copy
import time
import json

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, WeightedRandomSampler
from torchvision import datasets, transforms
from torchvision.models import (
    convnext_tiny,
    ConvNeXt_Tiny_Weights
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

LOCAL_CLS = Path("/content/Q-SENTINEL-CLS")

CLASS_NAMES = [
    "scratch",
    "blow_hole",
    "incomplete_welding",
    "bent_rim",
    "crack",
    "porosity",
    "scuff",
    "paint_damage"
]

NUM_CLASSES = len(CLASS_NAMES)

IMG_SIZE = 224
BATCH_SIZE = 32
NUM_WORKERS = 2

EPOCHS = 20
FREEZE_EPOCHS = 3

LEARNING_RATE_HEAD = 1e-3
LEARNING_RATE_BACKBONE = 1e-4

WEIGHT_DECAY = 1e-4
PATIENCE = 5

SEED = 42

torch.manual_seed(SEED)
np.random.seed(SEED)

print("Device:", DEVICE)
print("Classes:", NUM_CLASSES)
print("Image size:", IMG_SIZE)
print("Batch size:", BATCH_SIZE)
print("Epochs:", EPOCHS)

# ============================================================
# IMAGE TRANSFORMS
# ============================================================

weights = ConvNeXt_Tiny_Weights.DEFAULT

imagenet_mean = weights.transforms().mean
imagenet_std = weights.transforms().std

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),

    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.15),

    transforms.RandomRotation(
        degrees=15
    ),

    transforms.ColorJitter(
        brightness=0.15,
        contrast=0.15,
        saturation=0.10,
        hue=0.02
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=imagenet_mean,
        std=imagenet_std
    )
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=imagenet_mean,
        std=imagenet_std
    )
])

print("Transforms ready.")
print("ImageNet mean:", imagenet_mean)
print("ImageNet std :", imagenet_std)

# ============================================================
# LOAD TRAIN / VAL / TEST DATASETS
# ============================================================

train_dataset = datasets.ImageFolder(
    LOCAL_CLS / "train",
    transform=train_transform
)

val_dataset = datasets.ImageFolder(
    LOCAL_CLS / "val",
    transform=eval_transform
)

test_dataset = datasets.ImageFolder(
    LOCAL_CLS / "test",
    transform=eval_transform
)

print("Train:", len(train_dataset))
print("Val  :", len(val_dataset))
print("Test :", len(test_dataset))

print("\nImageFolder class mapping:")
print(train_dataset.class_to_idx)

assert train_dataset.class_to_idx == {
    cls: i for i, cls in enumerate(CLASS_NAMES)
}

# ============================================================
# Q-SENTINEL — LOAD DATASETS WITH CORRECT CLASS MAPPING
# ============================================================

from torchvision import datasets

# ------------------------------------------------------------
# Load datasets
# ------------------------------------------------------------

train_dataset = datasets.ImageFolder(
    LOCAL_CLS / "train",
    transform=train_transform
)

val_dataset = datasets.ImageFolder(
    LOCAL_CLS / "val",
    transform=eval_transform
)

test_dataset = datasets.ImageFolder(
    LOCAL_CLS / "test",
    transform=eval_transform
)

# ------------------------------------------------------------
# Use ImageFolder's actual alphabetical class mapping
# ------------------------------------------------------------

CLASS_TO_IDX = train_dataset.class_to_idx

CLASS_NAMES = [
    None
] * len(CLASS_TO_IDX)

for class_name, class_id in CLASS_TO_IDX.items():
    CLASS_NAMES[class_id] = class_name

NUM_CLASSES = len(CLASS_NAMES)

print("=" * 80)
print("DATASET MAPPING")
print("=" * 80)

print("Train:", len(train_dataset))
print("Val  :", len(val_dataset))
print("Test :", len(test_dataset))

print("\nClass-to-index:")
print(CLASS_TO_IDX)

print("\nIndex-to-class:")
for idx, name in enumerate(CLASS_NAMES):
    print(f"{idx}: {name}")

# ------------------------------------------------------------
# Verify validation/test mappings
# ------------------------------------------------------------

print("\nValidation mapping:")
print(val_dataset.class_to_idx)

print("\nTest mapping:")
print(test_dataset.class_to_idx)

assert val_dataset.class_to_idx == CLASS_TO_IDX, \
    "Validation class mapping does not match training mapping."

assert test_dataset.class_to_idx == CLASS_TO_IDX, \
    "Test class mapping does not match training mapping."

print("\n✅ Class mappings are consistent.")

# ============================================================
# BALANCED TRAINING SAMPLER
# ============================================================

train_targets = np.array(
    train_dataset.targets
)

class_counts = np.bincount(
    train_targets,
    minlength=NUM_CLASSES
)

print("Training class counts:")

for idx, cls in enumerate(CLASS_NAMES):
    print(
        f"{idx:2d}  {cls:25s} {class_counts[idx]}"
    )

# Square-root inverse frequency
class_weights = (
    1.0 / np.sqrt(
        np.maximum(class_counts, 1)
    )
)

# Normalize weights around 1
class_weights = (
    class_weights /
    class_weights.mean()
)

sample_weights = class_weights[
    train_targets
]

sampler = WeightedRandomSampler(
    weights=torch.as_tensor(
        sample_weights,
        dtype=torch.double
    ),
    num_samples=len(train_targets),
    replacement=True
)

print("\nSampler class weights:")

for idx, cls in enumerate(CLASS_NAMES):
    print(
        f"{cls:25s}: {class_weights[idx]:.3f}"
    )

# ============================================================
# DATALOADERS
# ============================================================

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    sampler=sampler,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

print("Train batches:", len(train_loader))
print("Val batches  :", len(val_loader))
print("Test batches :", len(test_loader))

# ============================================================
# QUICK DATA SANITY CHECK
# ============================================================

images, labels = next(iter(train_loader))

print("Batch image tensor:", images.shape)
print("Batch labels:", labels.shape)

print("\nLabel IDs in batch:")
print(torch.unique(labels).tolist())

assert images.ndim == 4
assert images.shape[1] == 3
assert images.shape[2] == IMG_SIZE
assert images.shape[3] == IMG_SIZE

print("\n✅ DataLoader sanity check passed.")

# ============================================================
# CONVNEXT-TINY MODEL
# ============================================================

model = convnext_tiny(
    weights=ConvNeXt_Tiny_Weights.DEFAULT
)

# ConvNeXt-Tiny classifier:
# Linear(768 -> 1000)
#
# Replace with our 8-class head.

in_features = model.classifier[-1].in_features

model.classifier[-1] = nn.Sequential(
    nn.Dropout(p=0.30),
    nn.Linear(in_features, NUM_CLASSES)
)

model = model.to(DEVICE)

print(model.classifier)

print(
    "\nFeature dimension before classifier:",
    in_features
)

# ============================================================
# LOSS + OPTIMIZER
# ============================================================

criterion = nn.CrossEntropyLoss(
    label_smoothing=0.1
)

optimizer = torch.optim.AdamW(
    filter(
        lambda p: p.requires_grad,
        model.parameters()
    ),
    lr=LEARNING_RATE_HEAD,
    weight_decay=WEIGHT_DECAY
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=EPOCHS
)

print("Loss      :", criterion)
print("Optimizer :", optimizer.__class__.__name__)
print("Scheduler :", scheduler.__class__.__name__)

# ============================================================
# TRAINING / EVALUATION FUNCTIONS
# ============================================================

def train_one_epoch(model, loader, criterion, optimizer):

    model.train()

    running_loss = 0.0
    all_preds = []
    all_labels = []

    for images, labels in loader:

        images = images.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )

        optimizer.zero_grad(
            set_to_none=True
        )

        outputs = model(images)

        loss = criterion(
            outputs,
            labels
        )

        loss.backward()

        optimizer.step()

        running_loss += (
            loss.item() *
            images.size(0)
        )

        preds = outputs.argmax(dim=1)

        all_preds.extend(
            preds.detach().cpu().numpy()
        )

        all_labels.extend(
            labels.detach().cpu().numpy()
        )

    epoch_loss = (
        running_loss /
        len(loader.dataset)
    )

    accuracy = accuracy_score(
        all_labels,
        all_preds
    )

    macro_f1 = f1_score(
        all_labels,
        all_preds,
        average="macro",
        zero_division=0
    )

    return epoch_loss, accuracy, macro_f1


@torch.no_grad()
def evaluate(model, loader, criterion):

    model.eval()

    running_loss = 0.0
    all_preds = []
    all_labels = []

    for images, labels in loader:

        images = images.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )

        outputs = model(images)

        loss = criterion(
            outputs,
            labels
        )

        running_loss += (
            loss.item() *
            images.size(0)
        )

        preds = outputs.argmax(dim=1)

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

    epoch_loss = (
        running_loss /
        len(loader.dataset)
    )

    accuracy = accuracy_score(
        all_labels,
        all_preds
    )

    macro_precision = precision_score(
        all_labels,
        all_preds,
        average="macro",
        zero_division=0
    )

    macro_recall = recall_score(
        all_labels,
        all_preds,
        average="macro",
        zero_division=0
    )

    macro_f1 = f1_score(
        all_labels,
        all_preds,
        average="macro",
        zero_division=0
    )

    return (
        epoch_loss,
        accuracy,
        macro_precision,
        macro_recall,
        macro_f1,
        np.array(all_labels),
        np.array(all_preds)
    )

# ============================================================
# CONVNEXT-TINY TRAINING
# ============================================================

history = []

best_f1 = -1
best_state = None
best_epoch = 0
epochs_without_improvement = 0

start_time = time.time()

for epoch in range(1, EPOCHS + 1):

    # --------------------------------------------------------
    # Unfreeze backbone after initial warm-up
    # --------------------------------------------------------
    if epoch == FREEZE_EPOCHS + 1:

        print(
            "\n🔓 Unfreezing ConvNeXt backbone..."
        )

        for param in model.features.parameters():
            param.requires_grad = True

        optimizer = torch.optim.AdamW(
            model.parameters(),
            lr=LEARNING_RATE_BACKBONE,
            weight_decay=WEIGHT_DECAY
        )

        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer,
            T_max=EPOCHS - FREEZE_EPOCHS
        )

    # --------------------------------------------------------
    # Train
    # --------------------------------------------------------
    train_loss, train_acc, train_f1 = train_one_epoch(
        model,
        train_loader,
        criterion,
        optimizer
    )

    # --------------------------------------------------------
    # Validation
    # --------------------------------------------------------
    (
        val_loss,
        val_acc,
        val_precision,
        val_recall,
        val_f1,
        val_labels,
        val_preds
    ) = evaluate(
        model,
        val_loader,
        criterion
    )

    scheduler.step()

    record = {
        "epoch": epoch,
        "train_loss": train_loss,
        "train_accuracy": train_acc,
        "train_macro_f1": train_f1,
        "val_loss": val_loss,
        "val_accuracy": val_acc,
        "val_macro_precision": val_precision,
        "val_macro_recall": val_recall,
        "val_macro_f1": val_f1
    }

    history.append(record)

    print(
        f"Epoch {epoch:02d}/{EPOCHS} | "
        f"Train Loss {train_loss:.4f} | "
        f"Train Acc {train_acc:.4f} | "
        f"Val Loss {val_loss:.4f} | "
        f"Val Acc {val_acc:.4f} | "
        f"Val Macro F1 {val_f1:.4f}"
    )

    # --------------------------------------------------------
    # Save best model based on Macro F1
    # --------------------------------------------------------
    if val_f1 > best_f1:

        best_f1 = val_f1
        best_epoch = epoch

        best_state = copy.deepcopy(
            model.state_dict()
        )

        epochs_without_improvement = 0

        print(
            f"  ✅ New best model — "
            f"Val Macro F1 = {val_f1:.4f}"
        )

    else:

        epochs_without_improvement += 1

    # --------------------------------------------------------
    # Early stopping
    # --------------------------------------------------------
    if epochs_without_improvement >= PATIENCE:

        print(
            f"\n⏹️ Early stopping at epoch {epoch}"
        )

        break

elapsed = time.time() - start_time

print("\n" + "=" * 80)
print("TRAINING COMPLETE")
print("=" * 80)

print("Best epoch :", best_epoch)
print("Best Val Macro F1:", round(best_f1, 4))
print("Training time:", round(elapsed / 60, 2), "minutes")

# ============================================================
# FINAL TEST EVALUATION
# ============================================================

if best_state is None:
    raise RuntimeError(
        "No best model checkpoint was created."
    )

model.load_state_dict(best_state)

(
    test_loss,
    test_acc,
    test_precision,
    test_recall,
    test_f1,
    test_labels,
    test_preds
) = evaluate(
    model,
    test_loader,
    criterion
)

print("=" * 80)
print("CONVNEXT-TINY TEST RESULTS")
print("=" * 80)

print(f"Test Loss            : {test_loss:.4f}")
print(f"Test Accuracy        : {test_acc:.4f}")
print(f"Test Macro Precision : {test_precision:.4f}")
print(f"Test Macro Recall    : {test_recall:.4f}")
print(f"Test Macro F1        : {test_f1:.4f}")

# ============================================================
# PER-CLASS CLASSIFICATION REPORT
# ============================================================

report = classification_report(
    test_labels,
    test_preds,
    labels=list(range(NUM_CLASSES)),
    target_names=CLASS_NAMES,
    zero_division=0,
    output_dict=True
)

report_df = pd.DataFrame(report).T

display(
    report_df.round(4)
)

# ============================================================
# CONFUSION MATRIX
# ============================================================

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(
    test_labels,
    test_preds,
    labels=list(range(NUM_CLASSES))
)

fig, ax = plt.subplots(
    figsize=(12, 10)
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=CLASS_NAMES
)

disp.plot(
    ax=ax,
    xticks_rotation=45,
    values_format="d"
)

ax.set_title(
    "Q-SENTINEL ConvNeXt-Tiny — Test Confusion Matrix"
)

plt.tight_layout()
plt.show()

# ============================================================
# SAVE CONVNEXT CHECKPOINT
# ============================================================

MODEL_DIR = PROJECT / "models"
MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

MODEL_PATH = MODEL_DIR / "convnext_tiny_8class_best.pth"

checkpoint = {
    "model_state_dict": model.state_dict(),
    "class_names": CLASS_NAMES,
    "num_classes": NUM_CLASSES,
    "best_epoch": best_epoch,
    "best_val_macro_f1": best_f1,
    "test_accuracy": test_acc,
    "test_macro_precision": test_precision,
    "test_macro_recall": test_recall,
    "test_macro_f1": test_f1
}

torch.save(
    checkpoint,
    MODEL_PATH
)

print("Saved ConvNeXt checkpoint:")
print(MODEL_PATH)

# ============================================================
# Q-SENTINEL — FINAL CONVNEXT TEST EVALUATION
# ============================================================

# Restore the best validation model
model.load_state_dict(best_state)

(
    test_loss,
    test_acc,
    test_precision,
    test_recall,
    test_f1,
    test_labels,
    test_preds
) = evaluate(
    model,
    test_loader,
    criterion
)

print("=" * 80)
print("CONVNEXT-TINY — FINAL TEST RESULTS")
print("=" * 80)

print(f"Test Loss            : {test_loss:.4f}")
print(f"Test Accuracy        : {test_acc:.4f}")
print(f"Test Macro Precision : {test_precision:.4f}")
print(f"Test Macro Recall    : {test_recall:.4f}")
print(f"Test Macro F1        : {test_f1:.4f}")

# ============================================================
# PER-CLASS PERFORMANCE
# ============================================================

report = classification_report(
    test_labels,
    test_preds,
    labels=list(range(NUM_CLASSES)),
    target_names=CLASS_NAMES,
    zero_division=0,
    output_dict=True
)

report_df = pd.DataFrame(report).T

display(
    report_df.round(4)
)

# ============================================================
# CONFUSION MATRIX
# ============================================================

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

cm = confusion_matrix(
    test_labels,
    test_preds,
    labels=list(range(NUM_CLASSES))
)

fig, ax = plt.subplots(figsize=(12, 10))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=CLASS_NAMES
)

disp.plot(
    ax=ax,
    xticks_rotation=45,
    values_format="d"
)

ax.set_title(
    "Q-SENTINEL ConvNeXt-Tiny — Test Confusion Matrix"
)

plt.tight_layout()
plt.show()

